
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: stepQuest-jenkins
    volumes:
      - ./jenkins:/app/jenkins_home
    ports:
      - "8081:8080"
    networks:
      - cicd-network

  sonarqube:
    image: sonarqube:latest
    container_name: stepQuest-sonarqube
    ports:
      - "9001:9000"
    volumes:
      - ./sonarqube:/app/sonarqube_home
    networks:
      - cicd-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: pallas
      MYSQL_DATABASE: step_quest
      MYSQL_USER: gaston
      MYSQL_PASSWORD: pallas
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - cicd-network

volumes:
  mariadb_data:

networks:
  cicd-network:
    driver: bridge
