name: stepQuest

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: stepQuest-jenkins
    volumes:
      - ./jenkins:/app/jenkins_home
    ports:
      - "8081:8080"
    networks:
      - cicd-network

  sonarqube:
    image: sonarqube:latest
    container_name: stepQuest-sonarqube
    ports:
      - "9001:9000"
    volumes:
      - ./sonarqube:/app/sonarqube_home
    networks:
      - cicd-network

  postgres-db:
    image: bitnami/postgresql:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: gaston
      POSTGRES_PASSWORD: pallas
      POSTGRES_DB: step_quest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cicd-network

volumes:
  postgres_data:

networks:
  cicd-network:
    driver: bridge